version: '3.8'

services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo
    environment:
      ADDONS_PATH: ${ADDONS_PATH:-/mnt/extra-addons}
      DATA_DIR: ${DATA_DIR:-/var/lib/odoo}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-odoo}
      DB_PASSWORD: ${DB_PASSWORD:-odoo}
      DB_NAME: ${DB_NAME:-postgres}
      ADMIN_PASSWD: ${ADMIN_PASSWD:-admin}
      CSV_INTERNAL_SEP: ${CSV_INTERNAL_SEP:-,}
      DB_MAXCONN: ${DB_MAXCONN:-64}
      DB_TEMPLATE: ${DB_TEMPLATE:-template1}
      DBFILTER: ${DBFILTER:-.*}
      DEBUG_MODE: ${DEBUG_MODE:-False}
      EMAIL_FROM: ${EMAIL_FROM:-False}
      LIMIT_MEMORY_HARD: ${LIMIT_MEMORY_HARD:-2684354560}
      LIMIT_MEMORY_SOFT: ${LIMIT_MEMORY_SOFT:-2147483648}
      LIMIT_REQUEST: ${LIMIT_REQUEST:-8192}
      LIMIT_TIME_CPU: ${LIMIT_TIME_CPU:-60}
      LIMIT_TIME_REAL: ${LIMIT_TIME_REAL:-120}
      LIST_DB: ${LIST_DB:-True}
      LOG_DB: ${LOG_DB:-False}
      LOG_HANDLER: ${LOG_HANDLER:-[:INFO]}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOGFILE: ${LOGFILE:-None}
      LONGPOLLING_PORT: ${LONGPOLLING_PORT:-8072}
      MAX_CRON_THREADS: ${MAX_CRON_THREADS:-2}
      OSV_MEMORY_AGE_LIMIT: ${OSV_MEMORY_AGE_LIMIT:-1.0}
      OSV_MEMORY_COUNT_LIMIT: ${OSV_MEMORY_COUNT_LIMIT:-False}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-False}
      SMTP_PORT: ${SMTP_PORT:-25}
      SMTP_SERVER: ${SMTP_SERVER:-localhost}
      SMTP_SSL: ${SMTP_SSL:-False}
      SMTP_USER: ${SMTP_USER:-False}
      WORKERS: ${WORKERS:-0}
      XMLRPC: ${XMLRPC:-True}
      XMLRPC_INTERFACE: ${XMLRPC_INTERFACE:-}
      XMLRPC_PORT: ${XMLRPC_PORT:-8069}
      XMLRPCS: ${XMLRPCS:-True}
      XMLRPCS_INTERFACE: ${XMLRPCS_INTERFACE:-}
      XMLRPCS_PORT: ${XMLRPCS_PORT:-8071}
    ports:
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: odoo_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
      POSTGRES_DB: ${POSTGRES_DATABASE:-postgres}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  odoo_data:
  pg_data:
